# Generated by Django 5.0.1 on 2024-01-24 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Name',
            new_name='Names',
        ),
    ]
