# Generated by Django 5.0.1 on 2024-01-26 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Workas',
        ),
        migrations.AlterField(
            model_name='crew',
            name='tconst',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='administrator.titlebasic'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='parentTconst',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='episode',
            name='tconst',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='administrator.titlebasic'),
        ),
        migrations.AlterField(
            model_name='principals',
            name='nconst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.names'),
        ),
        migrations.AlterField(
            model_name='principals',
            name='ordering',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='principals',
            name='tconst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.titlebasic'),
        ),
        migrations.AlterField(
            model_name='principals',
            name='workas_Id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rating',
            name='tconst',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='administrator.titlebasic'),
        ),
        migrations.AlterField(
            model_name='titleaka',
            name='aka_Id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='titleaka',
            name='ordering',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='titleaka',
            name='tconst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.titlebasic'),
        ),
        migrations.AlterField(
            model_name='titleaka',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='titlebasic',
            name='isAdult',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='titlebasic',
            name='startYear',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
