# Generated by Django 5.0.1 on 2024-01-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_rename_principal_principals_alter_names_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workas',
            fields=[
                ('workas_Id', models.AutoField(primary_key=True, serialize=False)),
                ('tconst', models.CharField(max_length=10)),
                ('ordering', models.IntegerField()),
                ('nconst', models.CharField(max_length=10)),
                ('category', models.CharField(blank=True, max_length=25, null=True)),
                ('job', models.CharField(blank=True, max_length=255, null=True)),
                ('characters', models.CharField(blank=True, max_length=255, null=True)),
                ('img_url_asset', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'workas',
            },
        ),
    ]
