# Generated by Django 5.0.1 on 2024-01-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NameObject',
            fields=[
                ('nconst', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('primaryName', models.CharField(blank=True, max_length=255, null=True)),
                ('imgUrl', models.CharField(blank=True, max_length=255, null=True)),
                ('birthYear', models.IntegerField(blank=True, null=True)),
                ('deathYear', models.IntegerField(blank=True, null=True)),
                ('primaryProfession', models.CharField(blank=True, max_length=255, null=True)),
                ('titleID', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nameObject',
            },
        ),
        migrations.CreateModel(
            name='TitleObject',
            fields=[
                ('tconst', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('titleType', models.CharField(blank=True, max_length=255, null=True)),
                ('originalTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('img_url_asset', models.CharField(blank=True, max_length=255, null=True)),
                ('startYear', models.IntegerField(blank=True, null=True)),
                ('endYear', models.IntegerField(blank=True, null=True)),
                ('titles', models.TextField(blank=True, null=True)),
                ('regions', models.TextField(blank=True, null=True)),
                ('genres', models.TextField(blank=True, null=True)),
                ('averageRating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('numVotes', models.IntegerField(blank=True, null=True)),
                ('nconsts', models.TextField(blank=True, null=True)),
                ('categories', models.TextField(blank=True, null=True)),
                ('primaryName', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'titleObject',
            },
        ),
    ]
