# Generated by Django 5.0.1 on 2024-01-24 11:19

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('tconst', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('directors', models.CharField(blank=True, max_length=255, null=True)),
                ('writers', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Crew',
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('tconst', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('parentTconst', models.CharField(max_length=11)),
                ('seasonNumber', models.IntegerField(blank=True, null=True)),
                ('episodeNumber', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Episode',
            },
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('nconst', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('primaryName', models.CharField(blank=True, max_length=255, null=True)),
                ('birthYear', models.IntegerField(blank=True, null=True)),
                ('deathYear', models.IntegerField(blank=True, null=True)),
                ('primaryProfession', models.CharField(blank=True, max_length=255, null=True)),
                ('knownForTitles', models.CharField(blank=True, max_length=255, null=True)),
                ('imgUrl', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Name',
            },
        ),
        migrations.CreateModel(
            name='NameObject',
            fields=[
                ('nconst', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('primaryName', models.CharField(blank=True, max_length=255, null=True)),
                ('imgUrl', models.CharField(blank=True, max_length=255, null=True)),
                ('birthYear', models.IntegerField(blank=True, null=True)),
                ('deathYear', models.IntegerField(blank=True, null=True)),
                ('primaryProfession', models.CharField(blank=True, max_length=255, null=True)),
                ('titleID', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nameObject',
            },
        ),
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('workas_Id', models.AutoField(primary_key=True, serialize=False)),
                ('tconst', models.CharField(max_length=10)),
                ('ordering', models.IntegerField()),
                ('nconst', models.CharField(max_length=10)),
                ('category', models.CharField(blank=True, max_length=25, null=True)),
                ('job', models.CharField(blank=True, max_length=255, null=True)),
                ('characters', models.CharField(blank=True, max_length=255, null=True)),
                ('img_url_asset', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Principal',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('tconst', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('averageRating', models.FloatField(blank=True, null=True)),
                ('numVotes', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Rating',
            },
        ),
        migrations.CreateModel(
            name='TitleAka',
            fields=[
                ('aka_Id', models.AutoField(primary_key=True, serialize=False)),
                ('tconst', models.CharField(max_length=10)),
                ('ordering', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('types', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes', models.CharField(blank=True, max_length=255, null=True)),
                ('isOriginalTitle', models.IntegerField()),
            ],
            options={
                'db_table': 'TitleAka',
            },
        ),
        migrations.CreateModel(
            name='TitleBasic',
            fields=[
                ('tconst', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('titleType', models.CharField(blank=True, max_length=255, null=True)),
                ('primaryTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('originalTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('isAdult', models.IntegerField()),
                ('startYear', models.IntegerField()),
                ('endYear', models.IntegerField(blank=True, null=True)),
                ('runtimeMinutes', models.IntegerField(blank=True, null=True)),
                ('genres', models.CharField(blank=True, max_length=255, null=True)),
                ('img_url_asset', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'TitleBasic',
            },
        ),
        migrations.CreateModel(
            name='TitleObject',
            fields=[
                ('tconst', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('titleType', models.CharField(blank=True, max_length=255, null=True)),
                ('originalTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('img_url_asset', models.CharField(blank=True, max_length=255, null=True)),
                ('startYear', models.IntegerField(blank=True, null=True)),
                ('endYear', models.IntegerField(blank=True, null=True)),
                ('titles', models.TextField(blank=True, null=True)),
                ('regions', models.TextField(blank=True, null=True)),
                ('genres', models.TextField(blank=True, null=True)),
                ('averageRating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('numVotes', models.IntegerField(blank=True, null=True)),
                ('nconsts', models.TextField(blank=True, null=True)),
                ('categories', models.TextField(blank=True, null=True)),
                ('primaryName', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'titleObject',
            },
        ),
    ]
