# Generated by Django 5.0.1 on 2024-01-24 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ntuaflix_api', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
